/*
 * curses_events.h
 *
 *  Created on: Dec 16, 2017
 *      Author: spider
 */

#ifndef APP_MAINAPP_INTERFACE_NCURSES_CURSES_EVENTS_H_
#define APP_MAINAPP_INTERFACE_NCURSES_CURSES_EVENTS_H_


#define CURSESAPP_EVENT_APP_INIT 0
#define CURSESAPP_EVENT_APP_CLOSE 0

#define CURSESAPP_EVENT_WINQUIZ_INIT 0
#define CURSESAPP_EVENT_WINQUIZ_CLOSE 0

#define CURSESAPP_EVENT_ABOUT_INIT 0
#define CURSESAPP_EVENT_ABOUT_CLOSE 0

#define CURSESAPP_EVENT_ADDQUIZ_INIT 0
#define CURSESAPP_EVENT_ADDQUIZ_CLOSE 0


#endif /* APP_MAINAPP_INTERFACE_NCURSES_CURSES_EVENTS_H_ */
